### PR TITLE
Smoke test https://dev.azure.com/msft-skilling/Content/_workitems/edit/198568

### PR DESCRIPTION
**Pull request by v-alje**

### CODE REVIEW

**Comment by twsouthwick** [comment]
@v-alje do we need to deal with the warnings? I'm good with merging in if we don't and then we can deal with the https://review.learn.microsoft.com/en-us/dotnet/api/overview/openxml/?view=openxml-3.0.1&branch=smoke-test page after

**Comment by v-alje** [comment]
@twsouthwick I would recommend going through the warnings and fixing them for the next NuGet release. 
I'll go ahead and merge.

**Comment by twsouthwick** [comment]
Are the expected fixes in the packages themselves? Is tthere a problem with the doc comments we have maybe?

**Comment by v-alje** [comment]
@twsouthwick Look at the [Build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6afb5089-e0f0-b79e-d95f-36d21fd417d1/202401100129162560-38/BuildReport?accessString=ac01e16f66d530f2e18f3e66f77002d65af9911c8e4dbfc4c6df66911c9d4dc4) for more warnings.  

The changes need to be made to the documentation in the /// XML comments which should get added to the NuGet packages as XML files at compile time. The documentation in the latest NuGet package overwrites the previous versions.

I don't know what is going on with the Moniker issues. That seems like it may be something weird about how the repo is configured.

Issues you can do something about is fix the broken seealso link and fix the remarks sections which point to an outdated URL for the Standard ECMA-376 spec. The URL 404s now. Since this was exported from a previous publishing system, it may be possible that you won't find these in the source code, you can try adding them to the source code, and if that does not work, you can edit the ECMAXML in this repo.

**Comment by twsouthwick** [comment]
Ok took a look at the warnings. The largest warning class is ECMA2Yaml_ExtraMonikerFoundInMember. These are all on types that we made a breaking change to convert an enum to a static class. For examples:

```csharp
public enum SomeEnum
{
  Value1,
  Value2,
}
```

became

```csharp
public static class SomeEnum
{
  public static readonly InterestingType Value1;

  public static readonly InterestingType Value2;
}
```

Is there a way to suppress this warning or a recommended way to fix this?

**Comment by twsouthwick** [comment]
Another class of errors are incorrect URLs such as here: https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.office2013.powerpoint.charttrackingreferencebased?view=openxml-2.8.1.

However, I do not see that remarks section anywhere and can't figure out where it comes from. Can you help with that?

**Comment by v-alje** [comment]
@twsouthwick for the converted types, I would recommend filing a bug at <https://sitehelp.microsoft.com/> selecting "Content authoring and publishing" and "Reference CI Jobs". I'm surprised mdoc was able to handle the changes from enum to static class. It seems like the publishing system needs to be updated to be able to handle it is well.

For the remarks sections you cannot find; the content of this repo was migrated from CAPS back in 2018. They are likely hand entered in CAPS and were copied over when migrated. You can try copying the remarks sections into the source code and fixing it there, or you can change the ECMAXML in this repo.

**Pull request merged**
